### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by lshengjian** [benhutchins/docker-taiga-example#1]
I found borswer Request URL:http://localhost:8000/api/v1/auth!
but my docker-compose.yml:

taiga:
  build: -t mytaiga .
  ports:
    - 80:80
    - 8000:8000

  links:
    - postgres
    - events
    - rabbit
    - redis
  environment:
    - TAIGA_HOSTNAME=192.168.1.178

my conf.json
{
    "api": "http://192.168.1.178:8000/api/v1/",
    "eventsUrl": null,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [""]

}

**Comment by benhutchins** [comment]
You'd get a login error with this setup, you need to configure the `TAIGA_HOSTNAME` and then it. Should be using http://192.168.1.178:8000/

It really cares about having the correct hostname.

**Comment by benhutchins** [comment]
Given that this ticket is a bit over a year old, I'll assume you've resolved it or moved on anyway, so going to close it. Sorry for the delay @lshengjian
