### ISSUE TITLE
What is default user?

### ISSUE THREAD

**Issue by Logos-Coder** [benhutchins/docker-taiga-example#20]
I have got the example running But I can't get anything useful out of it. All I get is this:
![Screenshot from 2019-06-19 14-05-20](https://user-images.githubusercontent.com/47828239/59796848-e8036b80-92cd-11e9-829a-93e2cc4ba9d1.png)
I can get to the login screen but I don't know of the default password.

I am on pop_os with docker 18.09.5

**Comment by AdamQuadmon** [comment]
admin
123123
