### ISSUE TITLE
error when docker-compose up

### ISSUE THREAD

**Issue by zhihuiFan** [benhutchins/docker-taiga-example#5]
could you help check what's wrong here?  

```
root@iZ23ryp9xr8Z:~/mytaiga/simple# docker-compose -v
docker-compose version 1.7.1, build 6c29830
root@iZ23ryp9xr8Z:~/mytaiga/simple# find . 
.
./README.md
./taiga-conf
./taiga-conf/local.py
./taiga-conf/conf.json
./docker-compose.yml
root@iZ23ryp9xr8Z:~/mytaiga/simple# docker-compose up
ERROR: build path /root/mytaiga/simple/benhutchins/taiga either does not exist, is not accessible, or is not a valid URL.
root@iZ23ryp9xr8Z:~/mytaiga/simple# docker images -a | grep taiga
benhutchins/taiga   latest              eb4d450dfecb        4 months ago        810.7 MB
```

**Comment by rikosjett** [comment]
Verify build path in docker-compose.yml.

**Comment by rsletta** [comment]
Please verify build path in docker-compose.yml.

**Comment by zhihuiFan** [comment]
thanks @rsletta  the docker-compose.yml is clone from this repo.   is there anything i need to change?

**Comment by rsletta** [comment]
> Disclaimer: I am a Docker newbie, to take my advise with a grain of salt, and don't get too angry if it doesn't magically fix everything. :)

From docker-compose.yml:
`
...

build: benhutchins/taiga

....`

This line reference the build context. As it stands there, it point towards av folder "benhutchins/taiga", relative to the parent folder of docker-compose.yml. This folder does not exist, as the error message says. Either create that folder (recurcive), or replace the line in docker-compose.yml with

`
...

build: .

....`

and then try running docker-compose up.

https://docs.docker.com/compose/compose-file/

**Comment by zhihuiFan** [comment]
Thanks @rsletta , this works

**Comment by thecraftman** [comment]
thanks  i had this issue too and it worked
