### ISSUE TITLE
Connection refused while connecting to upstream

### ISSUE THREAD

**Issue by Hounddog** [benhutchins/docker-taiga-example#6]
I have been trying to run the simple example and while trying to login and reading logs it get this error

taiga_1 | 2016/08/03 14:11:09 [error] 16#16: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "POST /api/v1/auth HTTP/1.1", upstream: "http://127.0.0.1:8000/api/v1/auth", host: "localhost", referrer: "http://localhost/login?next=%252Fdiscover"
taiga_1 | 172.17.0.1 - - [03/Aug/2016:14:11:09 +0000] "POST /api/v1/auth HTTP/1.1" 502 574 "http://localhost/login?next=%252Fdiscover" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36" "-"

**Comment by benhutchins** [comment]
Did you configure the `TAIGA_HOSTNAME` environment variable? It seems like you might have left it as `localhost` but then are requesting `127.0.0.1:8000`. That would cause problems with Taiga.
