### ISSUE TITLE
Problems with environments

### ISSUE THREAD

**Issue by jose2190** [benhutchins/docker-taiga-example#8]
When i run `docker-compose up`, i get this error, it's like the environment variables don't work properly

Attaching to simple_taiga_1
taiga_1     | Running database check
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in <module>
taiga_1     |     "' password='" + DB_PASS + "'")
taiga_1     | TypeError: Can't convert 'NoneType' object to str implicitly
taiga_1     | Failed to connect to database server or database does not exist.

But, in my `docker-compose.yaml` file,  **TAIGA_DB_PASSWORD** it's defined correctly

postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: test
  volumes:
    - ./data:/var/lib/postgresql/data

rabbit:
  image: rabbitmq:3
  hostname: rabbit

redis:
  image: redis:3

celery:
  image: celery
  links:
    - rabbit

events:
  image: benhutchins/taiga-events
  links:
    - rabbit

taiga:
  build: .
  ports:
    - 80:80
  links:
    - postgres
    - events
    - rabbit
    - redis
  environment:
    TAIGA_HOSTNAME: localhost
    TAIGA_DB_PASSWORD: test
    TAIGA_DB_HOST: postgres

  volumes:
    - ./media:/usr/src/taiga-back/media

Regards, peter.

**Comment by jose2190** [comment]
![ScreenShot](https://cloud.githubusercontent.com/assets/820859/23829131/51cecec8-06c7-11e7-801f-09d217cc31fc.png)
If i set `TAIGA_SLEEP` with 3000, i can inspect the container and run commands inside.
now comes the weird part, If i run `python checkdb.py` i get the same error than appears in docker-compose.yml, nothing new, but running python interactively i can access to te environment variables without problems.

**Comment by benhutchins** [comment]
Looks like you might not be defining `TAIGA_DB_NAME` (the database name, for postgres the default is `postgres`, see [Docker Hub](https://hub.docker.com/_/postgres/)) and `TAIGA_DB_USER` (might be `root` if you don't setup a user, also see the Docker Hub info for postgres).

You need to define all of these values for the script, none of them can be inferred anymore. Previously, Docker shared environmental variables with all linked containers, they have now deprecated that functionality and all these values must now be specified.

**Comment by zeroEvidence** [comment]
Ben, first off thank you for supplying a Taiga docker how to, it's muchly appreciated.

However, would it be possible to simplify the configuration of Taiga?
For example, getting rid of the simple and advanced version and providing the one that has both values with the advanced config commented out? 

Also could you provide a single config with all the mandatory configuration values in the one script please? E.g. "TAIGA_DB_NAME" is not listed as required anywhere in your repo's readme, it only says that it "can" be included. 

I've spent many, many hours banging my head against a brick wall and reading and rereading comments on docker, other Taiga docker image comments, all the readmes in the simple and advanced config folders, checking and rechecking my build, checking the docker manuals... getting really frustrated, only to come to the last resort to log an issue here to find a solution is already here from the 12/3/17 and now it's the 20/6/17, over three months and you haven't updated the comments in your readmes...

I am more than happy to help you supply better documentation, but I'm not in your head, could you please tell me what is required and what is not and I'll fork your repo and begin updating your documentation.

I'm sorry if the above does not read well, I have nothing but love in my heart for you and the work that you've done, I just don't know how else to put it at the moment.

Sincerely, thank you.

**Comment by benhutchins** [comment]
Thanks @zeroEvidence. I wasn't aware there was a problem with the documentation, this ticket was never resolved. I never heard back from @jose2190 so I was not aware the issue remained in the default examples. I took your suggestions and implemented them. Please feel free to continue improving this project, I only maintain it on the side now, so any assistance is appreciated.

**Comment by zeroEvidence** [comment]
@benhutchins Thank you! thank you! thank you!! I saw your changes! 

That's fair enough, again, sorry if I came across poorly.

**Comment by zeroEvidence** [comment]
You're a champion!!

**Comment by jose2190** [comment]
Hello! Sorry for my absence, I'm busy and I need days of 27hs hahaha
I just cloned the repository, and follow the steps one by one, and get the following error:
![captura de pantalla 2017-06-21 a la s 10 07 43](https://user-images.githubusercontent.com/820859/27385564-869a4d0c-5669-11e7-98ab-e5cc056b20fc.png)

**Comment by jose2190** [comment]
In the afternoon, I will try to fix it, greetings! Peter

**Comment by benhutchins** [comment]
@jose2190 That looks like a complaint about my awk command, but it still built the image correctly and successfully. Confusing though, I'll make a change to suppress that complaint.
